# this will throw an exception!
int("a")

print("Reached end of the program.")